# Created using 
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: WingetCreateE2E.PortableTest
PackageVersion: 1.2.3.4
MinimumOSVersion: 10.0.0.0
Installers:
- Architecture: x64
  InstallerType: portable
  InstallerUrl: https://fakedomain.com/WingetCreateTestExeInstaller.exe
  InstallerSha256: 71A2BF371B23C9432F4E0E08AE6F2A754067F0FE09C0141556DE4AF628F6B371
  Commands:
  - portableCommand
ManifestType: installer
ManifestVersion: 1.5.0
